### ISSUE TITLE
Size width of x_mem_req_t too limited - replace by byte enables

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-xif#17] opened 2021-10-18 07:01 UTC
The _size_ bitfield of x_mem_req_t needs to be update to support load/store widths as required per the v1.0 RISC-V 'V' Vector Extension. 

Also X_MEM_WIDTH should be adapted if needed to support the Vector spec.

**Comment by Silabs-ArjanB** [comment] 2022-01-18 08:41
Also not all access patterns are possible to express using 'size'. For example the Vector extension might want to perform a single transfer using a 4'b1010 byte enable mask.

The specification should be updated to use byte enables instead of size. The interaction between byte enables and alignment needs to be described.

**Comment by michael-platzer** [comment] 2022-01-26 15:27
A recent issue opened in the Vicuna repository ( vproc/vicuna#25 ) made me realize that replacing the `size` field with a byte enable mask introduces a problem with regards to memory alignment (although the problem is more general for a vector coprocessor). The current XIF spec states that:
> In case the memory request transaction results in a misaligned load/store operation, it is up to CPU how/whether misaligned load/store operations are supported.

If I understand this correctly, it is perfectly legal for a host CPU to reject misaligned memory operations by returning a synchronous misaligned load/store exception via the memory response interface.

However, if I read the RISC-V spec correctly, whether a memory address is misaligned or not depends on the size of the data type, rather than on XLEN or the width of the memory interface. An 8-bit value, for instance, can never be misaligned and a load/store of 8-bit values must never produce a misaligned load/store exception. Removing the `size` field means that this information is lost and the CPU can no longer decide whether the address is misaligned or not.

Memory alignment becomes particularly complicated when a vector coprocessor loads or stores several values at once, for instance 4 8-bit values packed into a 32-bit memory request. In this situation the `size` field is meaningless w.r.t. alignment. Because the values are 8-bit values, they cannot be misaligned and it is illegal to cause a load/store misaligned exception. This is also stated in the [RVV spec](https://github.com/riscv/riscv-v-spec/releases/download/v1.0/riscv-v-spec-1.0.pdf) in Sect. 8:
> If an element accessed by a vector memory instruction is not naturally aligned to the size of the element, either the element
is transferred successfully or an address misaligned exception is raised on that element.

However, if the coprocessor has no guarantee that the CPU will align the memory request to the width of the memory interface (since alignment of XIF memory requests is optional for the CPU), then it must do the alignment itself.

So, from the perspective of a vector coprocessor (as well as for any other coprocessor when replacing the `size` field with a byte enable mask) I see only two options:
- The host CPU must always align memory requests, since a request could consist of 8-bit data and thus a misaligned exception is not allowed.
- The XIF interface requires all memory transactions to be aligned to the width of the memory interface. Hence, the coprocessor is responsible for aligning its requests.

**Comment by bertwhl** [comment] 2022-04-14 14:01
Hello,
I also have a question regarding the signal 'size', I think its meaning is not clear with a larger memory width.

In the documentation, the signal 'size' is defined as below:
> Size of the memory transaction. 0: byte, 1: halfword, 2: word.

However, this define is only clear for 32-bit memory width, if the memory width is 64, 128, or 256, it is not enough to clarify the required size with only the three types "byte", "halfword", and "word".

Thank you very much!

**Comment by bertwhl** [comment] 2022-04-28 07:57
Thank you very much! The modification make sense to me!

**Comment by christian-herber-nxp** [comment] 2024-02-21 12:42
The problem seems to be addressed. Closing this issue

**Closed by christian-herber-nxp** 2024-02-21 12:42 UTC
Labels: memory-if
